### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by enriquejliconal** [JeffBeltran/sanctum-tokens#21]
Hi Jeff!

I'm Enrique and currently I'm using your package and it's very useful, thanks!. However it's necessary to be able to change language of all texts. There are some components that has hardcoded text:

![hardcoded-text](https://user-images.githubusercontent.com/52460714/101412915-05087180-38a9-11eb-8e89-0deffed54e7e.png)

So I would like to know if you can make a feature to add the internationalization?.

Thanks for your help!. I'll be waiting for your answer.

**Comment by JeffBeltran** [comment]
yeah i see no problem with that and i think it's a good idea, if i understand the docs this should be pretty easy. I'll take a look this weekend, but feel free to open a PR if you'd like

**Comment by JeffBeltran** [comment]
Hey @enriquejliconal i finally got around to figuring out how to to do this, sorry this was a bit harder to get working than i thought. I have never needed to work with localization before so if this doesn't work for you or you need some changes please let me know. Thanks!
