### ISSUE TITLE
Optional/Default Abilities Field

### ISSUE THREAD

**Issue by Theograms** [JeffBeltran/sanctum-tokens#25]
Hello Jeff,
Your package is great. 
I would like to ask you if you can make the Abilities field on the creation form hidden and maybe with default value.
Thank you for your work,
Theofanis

**Comment by JeffBeltran** [comment]
this seems doable, just out of curiosity what is the use case for this?

**Comment by Theograms** [comment]
The clients who use my Nova generate keys manually and register them to their own ERP so that it connects to my app. This field seems to confuse them while they generate a token and because the token must always has all abilities I would like to hide this field.

**Comment by JeffBeltran** [comment]
ah cool, interesting use case, tbh i never thought this would be used so it's interesting to hear other areas it's being utilized in. If i get some free time this week i'll dive into this as i think it will be nice to have a bit more configuration that can be customized.

**Comment by JeffBeltran** [comment]
Hey @Theograms new version should have the features you are looking for, let me know if you run into any issues

**Comment by Theograms** [comment]
Thank you @JeffBeltran, exactly what I needed! Have a nice day.
