### ISSUE TITLE
Incompatible with Nova 3.22

### ISSUE THREAD

**Issue by vbezruchkin** [JeffBeltran/sanctum-tokens#29]
Hi,

Thanks for the package.
I get  `TypeError: Cannot read property 'options' of undefined` when I click on Create token in Nova.

I also use Eminiarts/Tabs if that can help.

Please advise. Thanks

**Comment by JeffBeltran** [comment]
i can't duplicate this @vbezruchkin 

Currently trying it with 

```
laravel/framework (v8.30.1)
jeffbeltran/sanctum-tokens (v1.5.0)
laravel/nova (3.22.0)
```

can you provide more info or a repo i can look at and see?

**Comment by JeffBeltran** [comment]
I'm going to close this issue as i was unable to duplicate it, if you can provide me with some more info i'll try again
