### ISSUE TITLE
Unable to prepare route [nova-vendor/sanctum-tokens/tokens/{resourceName}/{id}] for serialization. Uses Closure

### ISSUE THREAD

**Issue by anibalsanchez** [JeffBeltran/sanctum-tokens#32]
Hi,

All routes are defined with clousures. So, `artisan optimize` or `artisan route:cache` can't be executed.

What do you recommend to solve the issue? Is it something that can be improved?

**Comment by JeffBeltran** [comment]
this is a good question, curious do you have other nova packages installed? might be the way we have this setup right now... I'd have to dive into this more and see. 

Did this only happen after adding this package?

**Comment by anibalsanchez** [comment]
> do you have other nova packages installed?

Yes

> Did this only happen after adding this package?

Yes, it looks like the routes in the package are all defined with Closures and not with a Controller. So, the cache generation fails.
