### ISSUE TITLE
Can not Create Token

### ISSUE THREAD

**Issue by 949mac** [JeffBeltran/sanctum-tokens#5]
Clicking the button does nothing.

![image](https://user-images.githubusercontent.com/23151962/84532542-42de6180-ac9b-11ea-8fc0-46e46c50dcd7.png)

**Comment by JeffBeltran** [comment]
hey thanks @949mac for the feedback, 

does this happen when you click on the "create token" button? or is this after you enter a name?

Also the way i have it right now is that it assumes your `User::class` is under the default `/app/` namespace. 

just trying to gather info so i could troubleshoot this from my end

Cheers

**Comment by JeffBeltran** [comment]
Hey @949mac i'm going to close this but if you can get me more info i'd be happy to take a look.

Thanks

**Comment by 949mac** [comment]
Hey -- sorry, a `php artisan optimize` fixed the issue. Thanks again!
