### ISSUE TITLE
nova 4 support

### ISSUE THREAD

**Issue by meyer59** [JeffBeltran/sanctum-tokens#63]

**Comment by JeffBeltran** [comment]
Thanks @meyer59 , it's on my todo list and I just moved over my side project to the new version so the plan is to do this soonish as i need it as well.

**Comment by meyer59** [comment]
Hello
Do you have any news about this ?

**Comment by JeffBeltran** [comment]
@meyer59 sorry nothing new to report. Been busy weekends for me so no time to jump on this

**Comment by samuelhautcoeur** [comment]
I'm eagerly waiting for this as well! Great package.

**Comment by JVercout** [comment]
Hi ! Also very interested to have an update for nova 4. 
Interested to participate to the upgrade if you need support ;)

**Comment by daugaard47** [comment]
Very much looking forward to this update.

**Comment by JeffBeltran** [comment]
sorry guys, this update is a bit of a slog, i have some of the basic updates working, but i need to completely redo the UI so it's going to take a bit of effort

**Comment by JeffBeltran** [comment]
well it "should" work for nova 4, i tested it locally and it worked but feel free to test it and let me know

**Comment by meyer59** [comment]
Hello
Seems to have some issue on the latest noa 4.11
![image](https://user-images.githubusercontent.com/9505463/176384541-95d1bd82-8add-4716-96dd-45e99258d88b.png)

```
exception: "Error"
file: "\vendor\\laravel\\nova\\src\\Fields\\HasOne.php"
line: 356
message: "Call to undefined method Laravel\\Nova\\ResourceToolElement::fillInto()"
```
