### ISSUE TITLE
Translation files location

### ISSUE THREAD

**Issue by vpratfr** [JeffBeltran/sanctum-tokens#76]
With Laravel 9, translation files are now by default located outside of the `resources` directory, directly under the project root folder.

If we move the published translation file to that location, then the strings do not appear translated.

Additionally, it would be nice to publish the translation file there instead of `resources/lang`.

**Comment by JeffBeltran** [comment]
thanks @vpratfr not sure when i'll get to this but i'll add it to my list. In the mean time if you want to take a stab at this feel free to open a PR

**Comment by hettiger** [comment]
I fixed this with https://github.com/JeffBeltran/sanctum-tokens/pull/86
