### ISSUE TITLE
Edit Abilities

### ISSUE THREAD

**Issue by CodeWithDennis** [JeffBeltran/sanctum-tokens#81]
Is it possible to edit abilities after creating a token?

**Comment by JeffBeltran** [comment]
i don't think that is a feature supported by sanctum out of the box, at least with a quick search and didn't see anything. 

That being said i would be open for a PR, but not sure we want to add it if this isn't supported by sanctum directly. i would just say the best way would be to create new token with the abilities you want and make the change that way
