### ISSUE TITLE
`<LoadingButton>` was removed in Nova 4

### ISSUE THREAD

**Issue by ralphschindler** [JeffBeltran/sanctum-tokens#92]
Conversation here: https://github.com/laravel/nova-issues/discussions/6025

**Comment by alancolant** [comment]
I've created a PR here, some nova packages are affected

**Comment by JeffBeltran** [comment]
Closing as it should have been resolved with releases https://github.com/JeffBeltran/sanctum-tokens/releases/tag/v2.0.4
