### ISSUE TITLE
Token is not displayed correctly in Modal, copying token after click does not work

### ISSUE THREAD

**Issue by webard** [JeffBeltran/sanctum-tokens#95]
Hello,

token in modal looks like this:
<img width="605" alt="image" src="https://github.com/JeffBeltran/sanctum-tokens/assets/855788/d05561b1-3135-4c82-b5eb-eb63c4392dc3">

and after clicking, there is info that I can copy by click, but nothing happens after clicking.

I have newest version of Laravel and Nova, without any special Laravel Nova plugins. Bug occurs on every browser.

**Comment by bluec** [comment]
Yep, the Modal component used has a default size of `xl`. The size can be passed in the props, e.g. CreatedTokenModal.vue could be modified as follows:

```vue
  <Modal :show="show" size="2xl">
```

**Comment by webard** [comment]
Good point. What about copying token after clicking? Did you look on this?

**Comment by bluec** [comment]
It's not my code, I have just been playing around with it. The copy when clicking works for me.

**Comment by JeffBeltran** [comment]
looks like they changed the input components on me (again) between version 4.24.2 => 4.32.16, i'll need to look into a fix

**Comment by webard** [comment]
I created a fork of your repository: https://github.com/webard/sanctum-tokens because I needed it in my project. It fixes:
- resized token modal to 4xl to fit token length
- fixed copying
- confirmation icon after copy
- couple style improvements
- integrated expiration date column from PR https://github.com/JeffBeltran/sanctum-tokens/pull/84
- visual fixes in dark mode

Copying feature works only in https, this should be noted in README.md, I thought it was an error, but it is limitation of browsers.

**Comment by JeffBeltran** [comment]
thanks @webard

With the copy issue, It's more a security issue than a browser issue, but no harm getting a note added there... eventually lol

**Comment by webard** [comment]
Yeah, I forgot that ClipboardAPI is available only on secured domain 😅. Just in case that other people wille report similar problems it is worth make note in readme.
